name: AI Code Review CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-review-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install System Dependencies for PDF Reports
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango-1.0-0 libpangocairo-1.0-0

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Linting (pylint)
        run: |
          pip install pylint
          pylint test.py || true

      - name: Run Java Linting (Checkstyle)
        run: |
          sudo apt-get install -y default-jre
          wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.2/checkstyle-10.12.2-all.jar
          wget -O google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml
          java -jar checkstyle.jar -c google_checks.xml test.java || true

      - name: Run JavaScript Linting (ESLint)
        run: |
          npm install -g eslint
          eslint test.js || true

      - name: Run Unit Tests with Pytest
        run: |
          pip install pytest
          pytest tests/ || true
